[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  let g:startify_change_to_vcs_root = 1
  let g:startify_change_to_dir = 0
  let g:startify_custom_header = ['']
  let g:startify_enable_special = 0
'''


# [[plugins]]
# repo = 'honza/vim-snippets'



[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/config/lightline.vim'


[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add = 'source ~/.config/nvim/config/lightline.vim'


# [[plugins]]
# repo = 'lyokha/vim-xkbswitch'
# hook_add = 'let g:XkbSwitchEnabled = 1'


[[plugins]]
repo = 'Yggdroot/LeaderF'
build = './install.sh'
hook_add = '''

  let g:Lf_HideHelp = 1
  let g:Lf_UseCache = 0
  let g:Lf_UseVersionControlTool = 0
  let g:Lf_IgnoreCurrentBufferName = 1
  let g:Lf_ShowDevIcons=0

  let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
  let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }



  let g:Lf_ShortcutF = "<leader>ff"
  noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
  noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
  noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
  noremap <leader>fs :<C-U><C-R>=printf("Leaderf rg --stayOpen %s", "")<CR><CR>

  xnoremap <leader>fs :<C-U><C-R>=printf("Leaderf! rg --stayOpen -F -e %s ", leaderf#Rg#visual())<CR>

  let g:Lf_CommandMap = {'<Tab>': ['<ESC>']}
  let g:Lf_DefaultMode = 'NameOnly'
  let g:Lf_PythonVersion=3
  let g:Lf_WindowHeight = 0.3
  let g:Lf_WorkingDirectoryMode = 'Ac'
  let g:Lf_GtagsAutoGenerate = 0
  let g:Lf_Gtagslabel = 'native-pygments'

  let g:Lf_WildIgnore = {
    \ 'dir': ['.svn','.git','.hg', 'node_modules', 'dist'],
    \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
    \}
  let g:Lf_MruWildIgnore = {
    \ 'dir': [],
    \ 'file': []
    \}
  let g:Lf_RgConfig = [
    \ "--max-columns=300",
    \ "--glob=!node_modules/*",
    \ "--glob=!dist/*",
    \ ]

'''



[[plugins]]
repo = 'kassio/neoterm'
hook_add = 'source ~/.config/nvim/config/terminal.vim'


[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = 'source ~/.config/nvim/config/nerdcommenter.vim'

# [[plugins]]
# repo = 'skywind3000/vim-keysound'
# hook_add = '''
# let g:keysound_theme = 'typewriter'
# let g:keysound_py_version = 3
# '''

# [[plugins]]
# repo = 'ludovicchabant/vim-gutentags'
# hook_source = '''
  # source ~/.vim/config/vim-gutentags.vim
# '''


# [[plugins]]
# repo = 'skywind3000/gutentags_plus'


[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'


[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'


[[plugins]]
repo = 'Valloric/ListToggle'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = '''
  let g:AutoPairsMapCh = 0
'''
