[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'
hook_add = '''
  nnoremap <silent> ยบ :Goyo<cr>
  nnoremap <silent> <leader><leader>0 :Goyo<cr>
'''
hook_source = '''
  let g:goyo_width=100
  let g:goyo_linenr=1
  autocmd! User GoyoEnter Limelight
  autocmd! User GoyoLeave Limelight!
'''


[[plugins]]
repo = 'junegunn/limelight.vim'
on_cmd = 'Limelight'


[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = 'GV'



[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = 'let g:vim_json_syntax_conceal = 0'


[[plugins]]
repo = 'honza/dockerfile.vim'
on_ft = 'Dockerfile'

# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'

[[plugins]]
repo = 'junegunn/vim-emoji'
on_ft = ['markdown','vim']


[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
#
[[plugins]]
repo = 'fs111/pydoc.vim'
on_ft = 'python'

# [[plugins]]
# repo = 'alfredodeza/pytest.vim'
# on_ft = 'python'


# [[plugins]]
# repo = 'othree/html5.vim'
# on_ft = ['html', 'javascript.jsx','vue','javascript']


# [[plugins]]
# repo = 'mxw/vim-jsx'
# on_ft = ['html', 'javascript.jsx','vue','javascript']
# hook_source = 'let g:jsx_ext_required = 0'


# [[plugins]]
# repo = 'ianks/vim-tsx'
# on_ft = ['html', 'javascript.jsx','vue','javascript']


# [[plugins]]
# repo = 'isRuslan/vim-es6'
# on_ft = ['html', 'javascript.jsx','vue','javascript', 'typescript']

# [[plugins]]
# repo = 'pangloss/vim-javascript'
# on_ft = ['html', 'javascript.jsx','vue','javascript']

# [[plugins]]
# repo = 'jelera/vim-javascript-syntax'
# on_ft = ['html', 'javascript.jsx','vue','javascript']


# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['javascript.jsx','vue']


# [[plugins]]
# repo = 'cakebaker/scss-syntax.vim'
# on_ft = ['scss']

# [[plugins]]
# repo = 'ap/vim-css-color'
# on_ft = ['css']


# [[plugins]]
# repo = 'octol/vim-cpp-enhanced-highlight'
# on_ft = 'cpp'
# hook_source = '''
  # let g:cpp_class_scope_highlight = 1
  # let g:cpp_member_variable_highlight = 1
  # let g:cpp_class_decl_highlight = 1
  # let g:cpp_experimental_simple_template_highlight = 1
  # let g:cpp_concepts_highlight = 1
# '''


[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'


# [[plugins]]
# repo = 'mattn/emmet-vim'
# on_ft = ['html','css','jsx','javascript','javascript.jsx']
# hook_add = '''
  # let g:user_emmet_install_global = 0
  # autocmd FileType html,css EmmetInstall
# '''

# [[plugins]]
# repo = 'jiangmiao/auto-pairs'
# on_event = 'InsertEnter'
# hook_add = '''
  # let g:AutoPairsMapCh = 0
  # let g:AutoPairsMapCR = 1
# '''



[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['python','html','css','vim','javascript','jsx','javascript.jsx','vue', 'cpp']
hook_source = '''
  let g:indentLine_fileTypeExclude = ['defx', 'denite','startify','tagbar','vista_kind']
'''


# [[plugins]]
# repo = 'ludovicchabant/vim-gutentags'
# on_path = '.*'
# on_if = "executable('ctags')"
# hook_source = '''
  # source ~/.config/nvim/config/vim-gutentags.vim
# '''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_path = '.*'
hook_source = '''
  autocmd BufReadPost fugitive://* set bufhidden=delete
'''


[[plugins]]
repo = 'tpope/vim-git'
on_path = '.*'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'
hook_source = '''

'''

# [[plugins]]
# repo = 'skywind3000/gutentags_plus'
# on_source = 'vim-gutentags.vim'


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['python','javascript','jsx','javascript.jsx','html','css','go','vim','toml','html','typescript']
hook_source = 'let g:rainbow_active = 1'


[[plugins]]
repo = 'airblade/vim-rooter'
on_path = '.*'
hook_source = 'let g:rooter_silent_chdir = 1'


[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
  nmap <silent> ยก :Defx<CR>
  nmap <silent> <leader><leader>1 :Defx<CR>
'''
hook_source = 'source ~/.config/nvim/config/defx.vim'


