[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'
hook_add = '''
  let g:goyo_width=100
  let g:goyo_height=80
  let g:goyo_linenr=1
  nnoremap <silent> ยบ :Goyo<cr>
  nnoremap <silent> <leader><leader>0 :<c-u>Goyo<cr>
'''
hook_source = '''
  autocmd! User GoyoEnter Limelight
  autocmd! User GoyoLeave Limelight!
'''

[[plugins]]
repo = 'junegunn/limelight.vim'
on_cmd = 'Limelight'


[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = 'GV'


[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = 'let g:vim_json_syntax_conceal = 0'



[[plugins]]
repo = 'honza/dockerfile.vim'
on_ft = 'Dockerfile'

# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'
# hook_add = '''
  # let g:go_def_mapping_enabled = 0
  # let g:go_template_autocreate = 0
  # let g:go_textobj_enabled = 0
  # let g:go_auto_type_info = 1
  # let g:go_def_mapping_enabled = 0
  # let g:go_highlight_array_whitespace_error = 1
  # let g:go_highlight_build_constraints = 1
  # let g:go_highlight_chan_whitespace_error = 1
  # let g:go_highlight_extra_types = 1
  # let g:go_highlight_fields = 1
  # let g:go_highlight_format_strings = 1
  # let g:go_highlight_function_calls = 1
  # let g:go_highlight_function_parameters = 1
  # let g:go_highlight_functions = 1
  # let g:go_highlight_generate_tags = 1
  # let g:go_highlight_methods = 1
  # let g:go_highlight_operators = 1
  # let g:go_highlight_space_tab_error = 1
  # let g:go_highlight_string_spellcheck = 1
  # let g:go_highlight_structs = 1
  # let g:go_highlight_trailing_whitespace_error = 1
  # let g:go_highlight_types = 1
  # let g:go_highlight_variable_assignments = 0
  # let g:go_highlight_variable_declarations = 0
  # let g:go_doc_keywordprg_enabled = 0
# '''

[[plugins]]
repo = 'junegunn/vim-emoji'
on_ft = ['markdown','vim']


# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ft = 'python'
#
# [[plugins]]
# repo = 'fs111/pydoc.vim'
# on_ft = 'python'

# [[plugins]]
# repo = 'alfredodeza/pytest.vim'
# on_ft = 'python'


[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript.jsx', 'javascript']


[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'javascript.jsx', 'javascript']


[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'javascript']


[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'javascript', 'javascript.jsx']


# [[plugins]]
# repo = 'othree/html5.vim'
# on_ft = ['html', 'javascript.jsx','vue','javascript']


# [[plugins]]
# repo = 'ianks/vim-tsx'
# on_ft = ['html', 'javascript.jsx','vue','javascript']


# [[plugins]]
# repo = 'isRuslan/vim-es6'
# on_ft = ['html', 'javascript.jsx','vue','javascript', 'typescript']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['html', 'javascript.jsx','vue','javascript']

# [[plugins]]
# repo = 'jelera/vim-javascript-syntax'
# on_ft = ['html', 'javascript.jsx','vue','javascript']


# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['javascript.jsx','vue']


# [[plugins]]
# repo = 'cakebaker/scss-syntax.vim'
# on_ft = ['scss']

# [[plugins]]
# repo = 'ap/vim-css-color'
# on_ft = ['css']



[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'


[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','jsx','javascript','javascript.jsx']
hook_add = '''
  let g:user_emmet_install_global = 0
'''
hook_source = '''
  autocmd FileType html,css EmmetInstall
'''



[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['python','html','css','vim','javascript','jsx','javascript.jsx','vue', 'cpp']
hook_add = '''
  let g:indentLine_color_term = 239
  let g:indentLine_color_gui = '#338833'
  let g:indentLine_bufTypeExclude = ['help', 'terminal']
  let g:indentLine_fileTypeExclude = ['defx', 'denite', 'startify', 'tagbar', 'vista_kind', 'help']
'''


# [[plugins]]
# repo = 'tpope/vim-fugitive'
# on_path = '.*'
# hook_source = '''
  # autocmd BufReadPost fugitive://* set bufhidden=delete
# '''


# [[plugins]]
# repo = 'tpope/vim-git'
# on_path = '.*'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'
# on_path = '.*'
# hook_source = '''
#
# '''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['python','javascript','jsx','javascript.jsx','html','css','go','vim','toml','html','typescript']
hook_source = 'let g:rainbow_active = 1'


[[plugins]]
repo = 'airblade/vim-rooter'
on_path = '.*'
hook_source = 'let g:rooter_silent_chdir = 1'


[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
  nmap <silent> ยก :<c-u>Defx -toggle<CR>
  nmap <silent> <leader><leader>1 :<c-u>Defx -toggle<CR>
'''
hook_source = 'source ~/.config/nvim/config/defx.vim'


